### ISSUE TITLE
Network Delay Time

### ISSUE THREAD

**Issue by saakshii12** [Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023-GDSC-CUMMINS-X-GDSC-MMCOE#91] opened 2023-09-30 17:50 UTC
**Write code in the preferred language and attach output with it.**

You are given a network of n nodes, labeled from 1 to n. You are also given times, a list of travel times as directed edges times[i] = (ui, vi, wi), where ui is the source node, vi is the target node, and wi is the time it takes for a signal to travel from source to target.

We will send a signal from a given node k. Return the minimum time it takes for all the n nodes to receive the signal. If it is impossible for all the n nodes to receive the signal, return -1.

**Example 1:**
![image](https://github.com/Google-Developer-Student-Club-CCOEW/Competitive-Programming-2023/assets/128240967/39aa8ecd-0fcd-4918-9545-dda71ae9b86d)
Input: times = [[2,1,1],[2,3,1],[3,4,1]], n = 4, k = 2
Output: 2

**Example 2:**

Input: times = [[1,2,1]], n = 2, k = 1
Output: 1

**Example 3:**

Input: times = [[1,2,1]], n = 2, k = 2
Output: -1

**Comment by 51tejalhajari** [comment] 2023-10-23 08:55
can you please assign this issue to me 
tejal hajari
cummins college of engineering pune
UEC2022151
tejal.hajari@cumminscollege.in

**Comment by bargeshreeya** [comment] 2023-10-31 04:24
hey @saakshii12 , i would like to contribute to this if the issue is still open ?
Roll No: UIT2021810

**Closed** 2023-10-31 14:42 UTC
Labels: good first issue, hacktoberfest2023, c, cpp, python, java, competitive programming, medium, graph, hacktoberfest, hacktoberfest-accepted
